// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4y8-tKiRVgAG5jesH9Jjq5YRRfDjSTyY',
    appId: '1:214068739537:web:c9a3e94961600025d5b4f0',
    messagingSenderId: '214068739537',
    projectId: 'aaa-online-registration-e3833',
    authDomain: 'aaa-online-registration-e3833.firebaseapp.com',
    storageBucket: 'aaa-online-registration-e3833.firebasestorage.app',
    measurementId: 'G-STBQTJMMVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWVL1KDHszJtsMy3PhKTOa35js6XN6OQ',
    appId: '1:214068739537:android:9d09f3185c06ea8dd5b4f0',
    messagingSenderId: '214068739537',
    projectId: 'aaa-online-registration-e3833',
    storageBucket: 'aaa-online-registration-e3833.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_M1x-9u29edLVVSsbBjChl_NjkP35XSM',
    appId: '1:214068739537:ios:8b566b9683733f6bd5b4f0',
    messagingSenderId: '214068739537',
    projectId: 'aaa-online-registration-e3833',
    storageBucket: 'aaa-online-registration-e3833.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_M1x-9u29edLVVSsbBjChl_NjkP35XSM',
    appId: '1:214068739537:ios:8b566b9683733f6bd5b4f0',
    messagingSenderId: '214068739537',
    projectId: 'aaa-online-registration-e3833',
    storageBucket: 'aaa-online-registration-e3833.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4y8-tKiRVgAG5jesH9Jjq5YRRfDjSTyY',
    appId: '1:214068739537:web:e51fd8f82667dd49d5b4f0',
    messagingSenderId: '214068739537',
    projectId: 'aaa-online-registration-e3833',
    authDomain: 'aaa-online-registration-e3833.firebaseapp.com',
    storageBucket: 'aaa-online-registration-e3833.firebasestorage.app',
    measurementId: 'G-BWDVVY8NYZ',
  );
}
